name: AWS EB Deploy

on:
  push:
    branches: [ "main" ]
    
jobs:
 deploy:
   runs-on: ubuntu-latest
   environment: aws-credentials
   
   steps:
   - name: Check out code
     uses: actions/checkout@v3
  
   - name: Generate deployment package
     run: zip deploy.zip Dockerrun.aws.json
  
   - name: Deploy to AWS Elastic BeanTalk
     uses: einaregilsson/beanstalk-deploy@v20
     with:
       aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       application_name: Private Bean
       environment_name: PrivateBean-env
       version_label: version-${{ github.sha }}
       use_existing_version_if_available: true
       wait_for_environment_recovery: 120
       region: eu-west-3
       deployment_package: deploy.zip
 
