name: Yghore et 🐻

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
    name: PHP ${{ matrix.php-versions }} unit tests on ${{ matrix.operating-system }}
    env:
      extensions: gd, sqlite3
      extensions-cache-key-name: phpextensions
      
    steps:
    - uses: actions/checkout@v3
    - name: Install composer
      run: composer install --prefer-dist --no-dev

    - name: Setup PHPunit
      run: composer install -n

    - name: Install Google Cloud Storage
      run: composer require google/cloud-storage

    # testing
    - name: Run unit tests
      run: XDEBUG_MODE=coverage ../vendor/bin/phpunit
      working-directory: tst
