name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker run --rm --read-only -v $GITHUB_WORKSPACE:/srv:ro privatebin/unit-testing

#    - name: Code Coverage Summary Report
#      uses: irongut/CodeCoverageSummary@v1.3.0
#      with:
#        filename: coverage.cobertura.xml
