name: PHP MD

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
    name: PHP ${{ matrix.php-versions }} unit tests on ${{ matrix.operating-system }}
    env:
      extensions: gd, sqlite3
      extensions-cache-key-name: phpextensions
      
    steps:
    - uses: actions/checkout@v3
    - name: Install composer
      run: composer install --prefer-dist --no-dev && npm i @wcj/html-to-markdown-cli -g

    - name: Setup PHP Mess Detector
      run: composer require "phpmd/phpmd"

    - name: Run Mess Detector
      run: ./vendor/bin/phpmd **/*.php --ignore-violations-on-exit html codesize | html-to-markdown >> $GITHUB_STEP_SUMMARY
