name: PHP CS

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']
    name: PHP ${{ matrix.php-versions }} unit tests on ${{ matrix.operating-system }}
    env:
      extensions: gd, sqlite3
      extensions-cache-key-name: phpextensions
      
    steps:
    - uses: actions/checkout@v3
    - name: Install composer
      run: composer install --prefer-dist --no-dev

    - name: Setup PHP Code Sniffer 👃👃👃
      run: composer require "squizlabs/php_codesniffer=*"

    - name: Run Code Sniffer
      run: ./vendor/bin/phpcs **/*.php --generator=markdown
